### ISSUE TITLE
[Makefile:24: secp256k1/.libs/libsecp256k1.a] Error 127 Kali Linux

### ISSUE THREAD

**Issue by byteking12** [ryancdotorg/brainflayer#100]
i am getting this error 
git submodule init
git submodule update
cd secp256k1; make distclean || true
make[1]: Entering directory '/root/brainflayer/secp256k1'
make[1]: *** No rule to make target 'distclean'.  Stop.
make[1]: Leaving directory '/root/brainflayer/secp256k1'
cd secp256k1; ./autogen.sh
./autogen.sh: 3: autoreconf: not found
make: *** [Makefile:24: secp256k1/.libs/libsecp256k1.a] Error 127

**Comment by ryancdotorg** [comment]
Please install the build dependencies for libsecp256k1 - that project has instructions.
