### ISSUE TITLE
sequentially scanning listed hex in a Batch file

### ISSUE THREAD

**Issue by asam007** [ryancdotorg/brainflayer#101]

**Comment by ryancdotorg** [comment]
Both sequential keyscan and search for raw private keys are supported.

Please read this guide to writing good bug reports: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Also note, per the readme:

> No support will be provided at this time, and I may ignore or close issues requesting support without responding.

**Comment by asam007** [comment]
Hi, I am trying to get to scan a series of arranged hex in a batch file just as we get on bitcrack
-i bit.txt --keyspace d068318a252852427e47c62a7e50166f281167f4d095aa1e4b0f0fd32341b66d:+5000
-i bit.txt --keyspace c068318a252852427e47c62a7e50166f281167f4d095aa1e4b0f0fd32341b66d:+5000
-i bit.txt --keyspace e068318a252852427e47c62a7e50166f281167f4d095aa1e4b0f0fd32341b66d:+5000

in a batch file so it can run a scan of 26million keys only on a particular keyspace and automatically move to the next line...

**Comment by ryancdotorg** [comment]
So this is a feature request to automatically stop in sequential scan mode after N keys?

Please see https://github.com/ryancdotorg/brainflayer/issues/56#issuecomment-412754995 for that.
