### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by kaanalican** [ryancdotorg/brainflayer#105]
I think there's an error.
seed this: craft lock give weird thought gorilla ring dove point turn forum veteran
Addresses produced from this seed:
16a8xZpYTAAMh5sFj5q1w3tBG6bD7nveEq
12jAyGWVXpc3NFAcXRJHDQnAdnwbvjkHF7
1KqAWVoNmf7P6fUeR2eHk8YneY5wGFL9Ra
1EJLkzPZkFgCukB4nrEtME1NFUNkMk48nT

A simple test.
Unfortunately, he can't find it when he makes a call.

am i missing something

**Comment by ryancdotorg** [comment]
This is an HD wallet scheme, brainflayer doesn't crack them.
