### ISSUE TITLE
Hyperthreading question

### ISSUE THREAD

**Issue by stereonov** [ryancdotorg/brainflayer#106]
Hello, just a quick question about huperthreading. I have an i7 4 cores CPU and using brainflayer with 4 terminals 1/4, 2/4, 3/4 and 4/4 to each. But while I was reading your instructions I notice "In my testing, brainflayer benefits significantly from hyperthreading, so you may want to run two copies per physical core", so the question is as an example I can open 8 terminals and add to 2 of them 1/4 and keep going without loose speed?

Thanks in advance!

**Comment by ryancdotorg** [comment]
Yes, you can do 1/8 - 8/8. Speed for individual instances will drop, perhaps (just as an example) by 40%, but then you have 60*8 = 480%. This may not be true any more with the meltdown/spectre mitigations, and could vary based on CPU in use.

**Comment by stereonov** [comment]
Great thank you very much for specification!
Last quick question please, also noticed from description "your_generator | brainflayer -v -b example.blf", I am using crunch to generate wordlists, tried to use it by adding all files of crunch into brainflayer directory and run "crunch command" | brainflayer -v -b example.blf but doesn't work. Am I do it wrong or doesn't support crunch? Maybe you can suggest some other generator.
Thanks again for your time, highly appreciated!
