### ISSUE TITLE
Command errors

### ISSUE THREAD

**Issue by cube305** [ryancdotorg/brainflayer#108]
I installed the brainflayer. I'm writing bloomfilter calculation code.

cd brainflayer
hex2blf example.hex example.blf
bash: hex2blf: No commands

----------
next code
brainflayer -v -b example.blf -i phraselist.txt
bash: hex2blf: No commands

Where am I making a mistake. it is very difficult to find people to support.

**Comment by daedalus** [comment]
Did you try? ./hex2blf

**Comment by cube305** [comment]
> Did you try? ./hex2blf

messi@messi-PC:~/brainflayer$ ./hex2blf
bash: ./hex2blf: No such file or directory               (  this is google translate  )
messi@messi-PC:~/brainflayer$ 

I have written everything in the following line of code. Some errors occurred.

How do I know if the brainflayer is working? I have the word txt file. how do you make private key search for these words.

`~$ sudo apt-get update
~$ sudo apt-get install build-essential
~$ sudo apt-get install git
~$ sudo apt-get install make
~$ sudo apt-get install autotools-dev
~$ sudo apt-get install zlib1g-dev
~$ sudo apt-get install libssl-dev
~$ sudo apt-get install libgmp-dev
~$ sudo apt-get install libtool
~$ sudo apt-get install autoconf
~$ sudo apt-get install automake
~$ sudo apt-get install pkg-config
~$ sudo apt-get install libgtk-3-dev
~$ git clone https://github.com/ryancdotorg/brainflayer.git
~$ make all
~$ ./brainflayer -h

~$ make all -lssl`

**Comment by ryancdotorg** [comment]
This seems to be a support request, not a bug report. Per the README:

> No support will be provided at this time, and I may ignore or close issues requesting support without responding.

Unfortunately I don't have time to walk anyone through compiling software and extracting data from the Bitcoin blockchain.

**Comment by cube305** [comment]
my aim is just to run brainflayer. I'm using google translate. hard to understand. nobody helped me.

I installed linux debian and ubuntu.

I have tried these codes in both linux. one, two code errors in the last row.

brainflayer installation on youtube site, no training videos to run. I want to use this software.


Do you want to help me? you can write an answer.

Don't you want to help? Don't write me the answer.

**Comment by su314ka** [comment]
Working ok on Ubuntu1804.
Make sure that below libraries are installed.

sudo apt-get install libgmp-dev libimobiledevice-dev libplist-dev libusbmuxd-dev libssl-dev dh-autoreconf

Example running:
cd /brainflayer
./brainflayer -v -I 927c1257fbb01080334f2eaddb814e09044ebb804d14f7e9c44801f1797c285f -b addresses.blf -o output.txt
or
./brainflayer -i input.txt -v -c u -b addresses.blf -o output.txt

./hex2blf addressed.hex addresses.blf
