### ISSUE TITLE
How to generate tab file with ecmtabgen?

### ISSUE THREAD

**Issue by stereo4** [ryancdotorg/brainflayer#111]
Hi, I'm looking to create a 'tabfile.tab' to share the same table in memory as you mention in your description.
I would like to add in this file `-n 1/4 -n 2/4 -n 3/4 -n 4/4` to save memory.
As you mention I should use it as `-m tabfile.tab` right?

But have no idea how to generate it, can you provide an example please?

P.s. On the below link I found the command `./ocmtabgen 575M tabfile.tab` but in return I get `bash: ./ocmtabgen: No such file or directory`.
https://github.com/TheRealLordFractal/Bip39Helper/issues/2#issuecomment-473051393

Thanks in advance!

**Comment by ryancdotorg** [comment]
The instructions you mentioned have multiple problems with them and were obviously not tested by the person who provided them.

It is `emctabgen` (with an **e**) not `omctabgen` and the second argument is the same window size arguemt (with the same caveats about initial memory use) as brainflayer's `-w` option.

Sensible window size values are 20, 22, 24, 26 or 29 depending on how much memory you have available.

**Comment by stereo4** [comment]
Thanks for help.
I have 8gb ram on my machine, so I tried:
`./emctabgen 29M tabfile.tab`
and I get:
`bash: ./emctabgen: No such file or directory`

**Comment by ryancdotorg** [comment]
There is no `M` in the argument. You need to use `20` if you have only 8GB of RAM, unless you want to enable swap space and give it a few hours to run with `22`.

It is supposed to be `./ecmtabgen`.

**Comment by stereo4** [comment]
Yes, I use `./ecmtabgen 20 tabfile.tab` and is generate the tabfile thank you!
But how I add into tabfile '-n 1/4 -n 2/4 -n 3/4 -n 4/4' ?
