### ISSUE TITLE
Upgrade to newest Ubuntu version

### ISSUE THREAD

**Issue by stereo4** [ryancdotorg/brainflayer#113]
Hey Ryan, as you have told me in the past, brainflayer can build only at Ubuntu 14.04, so I use that version with brainflayer successfully the last years.

What I wanted to ask, brainflayer will still work if I upgrade to latest Ubuntu version? (e.g. 20.04 LTS)

Thanks once again!

**Comment by stereo4** [comment]
Ryan seems to be busy, anyone else have been upgrate Ubuntu after build brainflayer from 14.04 to latest version?

Thanks in advance!

**Comment by ryancdotorg** [comment]
I don't think it will work in Ubuntu 20.04. I finally bought a new computer a few months ago and will upgrade it to Ubuntu 20.04 soon. Please see #112.

**Comment by stereo4** [comment]
Hey Ryan thanks for reply, the issue #112 is about build problem, I have already build and use brainflayer successfully at 14.04. The question is if I upgrade Ubuntu to latest version if brainflayer will remain work.
Please if you upgrade, kindly let me know.

Thanks in advance!

**Comment by siupune** [comment]
Any update for installing brainflayer in Ubutu 20.04?

**Comment by ryancdotorg** [comment]
I got Ubuntu 20.04 installed a few weeks ago and do have it building properly now on my system, and I've started cleaning up the commit history a bit. Should be updated soon.

**Comment by kuw13** [comment]
Can you make a setup for kali unix !

**Comment by kuw13** [comment]
We need a kali unix setup please

**Comment by siupune** [comment]
thanks....

**Comment by siupune** [comment]
hey,
          would you send me make file as i am already using ubuntu20.04 and
i had a set up of ubuntu 18.04....so i am guessing ubuntu 20.04 would be
faster.....!!!


thanks
