### ISSUE TITLE
im so damn confused

### ISSUE THREAD

**Issue by iCocoFit123** [ryancdotorg/brainflayer#119]
im so damn confused 
i have bean trying for the past 48 hrs to do everything to make it work but i just cant please someone help me fix this error 
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99  brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainv2.o algo/brainwalletio.o algo/keccak.o algo/sha3.o algo/warpwallet.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -lpthread -o brainflayer
/usr/bin/ld: /tmp/brainflayer.T1M6TA.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x2265): undefined reference to `bloom_chk_hash160'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1
root@kali:~/brainflayer#

_Originally posted by @iCocoFit123 in https://github.com/ryancdotorg/brainflayer/issues/30#issuecomment-690806326_

**Comment by ryancdotorg** [comment]
I'm already aware this doesn't build on newer Linux distros, I'll fix it when I fix it.

**Comment by iCocoFit123** [comment]
Ryan could u please atleast tell me what i have to do ? 


Sent from Yahoo Mail for iPhone


On Friday, September 11, 2020, 10:29 AM, Ryan Castellucci <notifications@github.com> wrote:




I'm already aware this doesn't build on newer Linux distros, I'll fix it when I fix it.
