### ISSUE TITLE
Not running/No output

### ISSUE THREAD

**Issue by joncostello06** [ryancdotorg/brainflayer#12]
Hi,

After completely install all requirements like gmp, secp256k1 etc. I make test with basic command on Readme file. but there not output.
please check out this screenshot http://i.imgur.com/tpYb3Es.jpg

thank you

**Comment by ryancdotorg** [comment]
Brainflayer doesn't output anything unless there is a match if you supply a bloom filter.

**Comment by ryancdotorg** [comment]
There is now a -v option that will cause a status display to be shown on stderr.
