### ISSUE TITLE
Brainflayer command missing from bin? brainflayer -h and other commands not found 

### ISSUE THREAD

**Issue by btc99** [ryancdotorg/brainflayer#126]
my brainflayer commands are not working please help me. the program is already compiled no make error. any help would be really appreciated, thank you.

**Comment by btc99** [comment]
this is also what happens if i try "./brainflayer -h

Segmentation fault (core dumped)

**Comment by ryancdotorg** [comment]
I'm not sure how that could be happening? It doesn't even allocate memory if you just ask for the usage screen like that.

**Comment by btc99** [comment]
I'm gonna reinstall Ubuntu on a fresh machine and see if there's any changes

**Comment by btc99** [comment]
Its still doing the exact same, No clue why.

**Comment by btc99** [comment]
Ok i figured out the problem i believe. I'm missing the commands in the bin folder. How can I download one or create one?

**Comment by Solpadein911** [comment]
Ubuntu 20.04. After installation I have these problems brainslayer-h and other command not found Please help solving the problem!?
