### ISSUE TITLE
hex2blf error

### ISSUE THREAD

**Issue by balasid1404** [ryancdotorg/brainflayer#127]
when i type hex2blf it says no directory or file

**Comment by ryancdotorg** [comment]
Please provide more detail. A good article on how to write a good bug report can be foun here: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by balasid1404** [comment]
When I run hex2blf and then the desired file and location it says error
can't find file or directory

**Comment by kuw13** [comment]
Its not working

**Comment by Alf71** [comment]
Nice software.
Is it possible to simply copy paste a working version of Brainflayer into a different system?
I still don't know why, but I was able to install Brainflayer in VMWare Xubuntu, using commands
------------------------
$ git clone https://github.com/matchv/brainflayer.git
$ apt-get install openssl
$ apt-get install libgmp3-dev
$ apt-get install libimobiledevice-dev libplist-dev libusbmuxd-dev libssl-dev zlib1g-dev
$ apt-get install dh-autoreconf
$ cd brainflayer/
$ make 
------------------------
I tried the same by installing Kali and Ubuntu in Windows, but I allways receive error messages, among others:
"Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1"

**Comment by ryancdotorg** [comment]
> When I run hex2blf and then the desired file and location it says error can't find file or directory

This description is ambiguous - it's unclear whether your shell is giving an error trying to find the `hex2blf` binary or if this is some error message from hex2blf itself.

**Comment by ryancdotorg** [comment]
@Alf71 If you have a different problem, please comment on an existing issue that matches your problem (if you can find one), or open a new issue rather than replying to an arbitrary issue.

**Comment by balasid1404** [comment]
root@kali:~/brainflayer# ./hex2blf
bash: ./hex2blf: No such file or directory

i can add the file as argument but it says the same

**Comment by balasid1404** [comment]
gotcha kali linux aint supported
