### ISSUE TITLE
Bloom filter for Ethereum: With or without prefix 0x?

### ISSUE THREAD

**Issue by Alf71** [ryancdotorg/brainflayer#128]
Hi,

How do I create the ETH bloom filter? An shall I use a list containing ETH addresses with the prefix 0x or without the prefix 0x?

I'm getting the error message "failed to open bloom filter 'eth.blf': Permission denied" when using it with this command

 "sudo python generate.py -n 500 -w words.txt | ../brainflayer/brainflayer -c e -v -b eth.blf -o foundether.txt"

It works perfectly with BTC using a similar command, and also with ethereum, using hex key search:

sudo ./brainflayer  -c e -v -b eth.blf -I 4ce0b869ec0b4b278b9d69b86e02de76df903743a2fff677a6676c04a98b14c5 -o foundether.txt

or even

sudo ./brainflayer -c e -v -b eth.blf -i words.txt -o foundether.txt

**Comment by ryancdotorg** [comment]
It's without the `0x` prefix. In the first command you're not running brainflayer via sudo (which doesn't pass through to piped commands). There's no need to run any of these tools as root.

**Comment by ryancdotorg** [comment]
try `sudo echo | whoami` vs `sudo whoami` or `sudo sh -c 'echo | whoami'`

**Comment by Alf71** [comment]
> 
> 
> It's without the `0x` prefix. In the first command you're not running brainflayer via sudo (which doesn't pass through to piped commands). There's no need to run any of these tools as root.

It isn't working!  ;)

![grafik](https://user-images.githubusercontent.com/7470579/100087507-256b1180-2e4f-11eb-9e29-71e65c2cc49d.png)

**Comment by Alf71** [comment]
> It's without the `0x` prefix. In the first command you're not running brainflayer via sudo (which doesn't pass through to piped commands). There's no need to run any of these tools as root.

![grafik](https://user-images.githubusercontent.com/7470579/100088247-1afd4780-2e50-11eb-9243-b355aaa4b5b8.png)

**Comment by Alf71** [comment]
> `sudo echo | whoami` vs `sudo whoami` or `sudo sh -c 'echo | whoami'`

![grafik](https://user-images.githubusercontent.com/7470579/100088787-f6ee3600-2e50-11eb-8fb9-9e93bc0e8fbc.png)

**Comment by ryancdotorg** [comment]
run `sudo chown -R admin7 ~/brainflayer` and then stop using sudo.

**Comment by Alf71** [comment]
> 
> 
> run `sudo chown -R admin7 ~/brainflayer` and then stop using sudo.

The point is: If it is working with BTC (first command) why doesn't work with ETH (second command)?

sudo python brain12words.py -n 5000000000000000000000000000 -w chinese_simplified.txt | ../brainflayer/brainflayer -c cu -v -b btc_h160.blf -f btc_h160.bin -o foundbtc.txt

sudo python brain12words.py -n 5000000000000000000000000000 -w chinese_simplified.txt | ../brainflayer/brainflayer -c e -v -b eth.blf -o foundether.txt

**Comment by Alf71** [comment]
Wait...

**Comment by edw3m** [comment]
I simply can'y see what is missing. Please give me a clue ...

I can run it  against a phraselist: 
./brainflayer -c e -v -b eth_a.blf -i wordlist.txt -o eth.key
 rate:    319.31 p/s found:     1/5          elapsed:    0.016 s
 
But when trying to run it from stdin it won't work; I've tried hex64 and even phrase, 0x in front etc.:

echo -n "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b eth_a.blf -o eth.key
 rate:     63.36 p/s found:     0/1          elapsed:    0.016 s

echo -n "0xc4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b eth_a.blf -o eth.key

echo -n "correct horse battery staple" |./brainflayer -c e -v -b eth_a.blf -o eth.key                   
 rate:     64.57 p/s found:     0/1          elapsed:    0.015 s
 
 
What type of input it expects from stdin?

Great tool by the way!

**Comment by edw3m** [comment]
Tried mode options 👍 

python3 randomhex.py 1000000 |./brainflayer -v -c e -b eth_a.blf -t priv -x >> btc.key

echo -n "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b ../.eth/eth_a.blf -o eth.key
echo -n "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b ../.eth/eth_a.blf -t priv -x -o eth.key
echo -n "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b ../.eth/eth_a.blf -t keccak -x -o eth.key
echo -n "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a" |./brainflayer -c e -v -b ../.eth/eth_a.blf -t sha256 -x -o eth.key

None works; Ubuntu 20.04
