### ISSUE TITLE
Compiling error, please excuse my rookie tendencies im new to this, but i cant get to the bottom of these reference errors

### ISSUE THREAD

**Issue by calinative707** [ryancdotorg/brainflayer#13]
root@KALINATIVE:~/Downloads/brainflayer-master# make
gcc -O3 -flto -pedantic -std=gnu99 -Wall -Wextra -funsigned-char -Wno-pointer-sign -Wno-sign-compare -c warpwallet.c -o warpwallet.o
gcc -O3 -flto -pedantic -std=gnu99 -Wall -Wextra -funsigned-char -Wno-pointer-sign -Wno-sign-compare -c brainwalletio.c -o brainwalletio.o
gcc -O3 -flto -pedantic -std=gnu99 -Wall -Wextra -funsigned-char -Wno-pointer-sign -Wno-sign-compare -c brainv2.c -o brainv2.o
cd scrypt-jane; gcc -O3 -DSCRYPT_SALSA -DSCRYPT_SHA256 -c scrypt-jane.c -o scrypt-jane.o
gcc -O3 -flto -pedantic -std=gnu99 -Wall -Wextra -funsigned-char -Wno-pointer-sign -Wno-sign-compare -static brainflayer.o hex.o bloom.o warpwallet.o brainwalletio.o brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -ldl -lgmp -o brainflayer
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/cck0clOv.ltrans0.ltrans.o: In function `hexpass2hash160.lto_priv.6':
cck0clOv.ltrans0.o:(.text+0x142): undefined reference to `secp256k1_ecdsa_pubkey_create'
/tmp/cck0clOv.ltrans0.ltrans.o: In function `hexpriv2hash160.lto_priv.7':
cck0clOv.ltrans0.o:(.text+0x33a): undefined reference to `secp256k1_ecdsa_pubkey_create'
/tmp/cck0clOv.ltrans0.ltrans.o: In function `pass2hash160.lto_priv.5':
cck0clOv.ltrans0.o:(.text+0x55d): undefined reference to `secp256k1_ecdsa_pubkey_create'
/tmp/cck0clOv.ltrans0.ltrans.o: In function `bwiopass2hash160.lto_priv.11':
cck0clOv.ltrans0.o:(.text+0x7b1): undefined reference to `secp256k1_ecdsa_pubkey_create'
/tmp/cck0clOv.ltrans0.ltrans.o: In function `bwiosalt2hash160.lto_priv.10':
cck0clOv.ltrans0.o:(.text+0xa19): undefined reference to `secp256k1_ecdsa_pubkey_create'
/tmp/cck0clOv.ltrans0.ltrans.o:cck0clOv.ltrans0.o:(.text+0xc2f): more undefined references to `secp256k1_ecdsa_pubkey_create' follow
/tmp/cck0clOv.ltrans1.ltrans.o: In function `main':
cck0clOv.ltrans1.o:(.text.startup+0x279): undefined reference to `secp256k1_start'
cck0clOv.ltrans1.o:(.text.startup+0x8ef): undefined reference to `secp256k1_stop'
collect2: error: ld returned 1 exit status
Makefile:43: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

**Comment by Jul1u5** [comment]
Looks like you are using a mac, right? Won't work there...

**Comment by ryancdotorg** [comment]
Issue invalidated by commit f1e034d9
