### ISSUE TITLE
The same error while compile...again and again...I'm so frusted

### ISSUE THREAD

**Issue by hevn719** [ryancdotorg/brainflayer#130]
![16064659947934004203538434067354](https://user-images.githubusercontent.com/54221219/100427988-e692c100-30c5-11eb-869e-989d60085a64.jpg)

I had the same error again when compile for Ubuntu20.
Help me whats wrong here...I do some mistakes or something else. Please help me sir. I have do step by step like your rule.
@ryancdotorg

**Comment by ryancdotorg** [comment]
You're following instructions from someone else which are wrong.
