### ISSUE TITLE
Segwit Support

### ISSUE THREAD

**Issue by Napulsnik** [ryancdotorg/brainflayer#134]
Hello. Please add support for segwit addresses that start with "3" and "bc1"

**Comment by ryancdotorg** [comment]
bc1 addresses will work fine using compressed public key mode if you extract the hash160. I will see about adding support for P2SH-P2WPKH addresses, should be doable.

**Comment by Napulsnik** [comment]
Thank you.

**Comment by ryancdotorg** [comment]
Figured out how to handle P2SH-P2WPKH as well. Need to merge a bunch of my old unreleased work as dependencies though, so may take some time.

**Comment by Napulsnik** [comment]
Thank you for continuing to support the project.

**Comment by 2595raven** [comment]
I was wondering how it works with the different lengths available for bc1 addresses - example:
address:  bc1q3qpt7g4nn54pqswum5hezuygg2lyvyy9eshzgh
hash160:  8802bf22b39d2a1041dcdd2f91708842be461085
address:  1DQABvofrTfkG39GQmzqVCAoTwQNmPfy1q
hash160:  8802bf22b39d2a1041dcdd2f91708842be461085
These two addresses both resolve to the same hash with length 40 characters

This bc1 address is longer and the hash is 62 characters. This will not be picked up by hashing any compressed "1" address; or am I wrong?
address:  bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24sq90ecnvqqjwvw97
hash160:  4364063fac8829a931a752ecd9049e43425e2cebf83681876c556002bf389b00

**Comment by seokchul-kwon** [comment]
I am sending you a message because I have a question.
I'd like to know if the h160 bc1 address is supported for the version that is currently being provided. In particular, you predicted P2SH-P2WPKH support, so please let me know when you will release the additional version.

**Comment by tkredbaron** [comment]
what's the command to get my private key from my lost segelt Adresse?

**Comment by ryancdotorg** [comment]
@tkredbaron Not possible unless you generated it with a broken tool.

segwit support is in the develop branch

**Comment by ebookx** [comment]
I tried to compile the develop branch, it does  not compile and raise errors.
