### ISSUE TITLE
Whether Bitcoin addresses starting with bc1 are supported

### ISSUE THREAD

**Issue by seokchul-kwon** [ryancdotorg/brainflayer#136]
The person who uses brainflayer to detect private keys. I am using the software you provided well and admiring your skills. Currently, Bitcoin has addresses that start with 1, 3, and bc1, which are fixed at 40 bits of RIPEMD160 dml for 1 and 3, while addresses that start with bc1 have a RIPEMD160 value well above 40 bits. In this case, I wonder if the brainflayer is supported. Please reply. Thank you.

**Comment by seokchul-kwon** [comment]
The same question exists and is considered to have already been answered and closed. Thank you.

**Comment by kenorb** [comment]
Yes, it's supported. You've to convert them into hex representation with fixed length.

**Comment by seokchul-kwon** [comment]
Thank you for answering the old question.
Does the fixed length you mentioned mean RIPEMD160? In the case of bc1, it has a fixed length of about 60 bits or more, and in this case, I wonder if it is possible to detect with RIPEMD160 value in bc1.

If so, I wonder if the brainflayer has been upgraded.
