### ISSUE TITLE
Where do I add the addresses?

### ISSUE THREAD

**Issue by oguzdelioglu** [ryancdotorg/brainflayer#141]
c11e8406796ea352075234a0d50df5db7c46b3c2
ab7e21d65f521e163884d81aea511ec69ef98e46
462e1f7a4a5cd8492cea59d5c4d5e11932502678
d63a5fe438b61a2bb266dff616568b5ec7b1bd8f
b99862ff6ef6b684936fe1626bda31eebbc9d3f0
7cd9347d6e68c85cfe91ff387212d5ebd6d5370d
177a53b6eeed7c4094ea2c4c494adbe106d5d7ac
21c81a7464652486531625108df9b5728fb10110
c8bd7e593131a86a7734f907f32dbe92b5f4fce7
d3692ad7412becbefec7713c43e5a646cdd77b98
0e86a4e84164e4a52572fa8e6729c9014106c8b8
d1b0889f4670567a62d2f2ea063b9d5c1bda6d53
83ba53b0add5a00479a791d166161244dfb25dca
d7a569c0619a5b5eb1a08f068bc265dcc89d6f07
a93edadecca1168ded53242dec7a1d188a11e933
626cb4e0e213e66d0036596076c9ccbf4b68d542
6c216b2058d091a97d13af0c1f7dc85a66992f44
8610efb039f75bd8df3e8694693a03d9d7030005
9c0bc073af574cd7670777c401ad43b33535dc7d
975db601575895c656fdd36902bfb46a109eda09

Where exactly do you get them?
I have a list of balance wallet addresses.
How can I import them into the program?

**Comment by Napulsnik** [comment]
You need to write these addresses into a file for example "hash160".
Then execute the command:
~/brainflayer/hex2blf hash160 bloom.blf

**Comment by oguzdelioglu** [comment]
> You need to write these addresses into a file for example "hash160".
> Then execute the command:
> ~/brainflayer/hex2blf hash160 bloom.blf

For Example
I have these
18LQX6gCRaw64gtAv7aUbuhiXhTsKRRs3G
18LQX9bRRWRxn1hLBm29i2ehJgyR8nmpMt
hex2blf wallet.txt bloom.blf


is it true?

**Comment by Napulsnik** [comment]
Yes, but the address format must be "RIPEMD160". In your first message, the addresses are in the correct format.

**Comment by oguzdelioglu** [comment]
> Yes, but the address format must be "RIPEMD160". In your first message, the addresses are in the correct format.


they are sample codes of the project.

I want to bloom the public address list.
Example: 18LQX6gCRaw64gtAv7aUbuhiXhTsKRRs3G

**Comment by Napulsnik** [comment]
You need to convert them to RIPEMD160

**Comment by Napulsnik** [comment]
This tool can convert - https://github.com/matja/bitcoin-tool

**Comment by oguzdelioglu** [comment]
> You need to convert them to RIPEMD160


I wonder if there is a code in this project where I can do this?

**Comment by Napulsnik** [comment]
See the post above

**Comment by Napulsnik** [comment]
You will need to execute the command:

`~/bitcoin-tool/bitcoin-tool --batch --input-type address --output-type public-key-rmd --input-format base58check --network bitcoin --output-format hex --input-file '~/wallet.txt' > ~/hash160`

**Comment by oguzdelioglu** [comment]
> You will need to execute the command:
> 
> `~/bitcoin-tool/bitcoin-tool --batch --input-type address --output-type public-key-rmd --input-format base58check --network bitcoin --output-format hex --input-file '~/wallet.txt' > ~/hash160`

Public Address
1zzzbRUbAnKUAJ6fEhX1g1ZzMz6ur3BJW

Hash160
0af81eb3ee49100ea0cddd720f2dfb35dc75df6b

Hash160 to bloom
./hex2blf hash160.txt bloom.blf


Finally I can run this code and start it, right?
./brainflayer -v -i dictionary.txt -b bloom.blf

**Comment by Napulsnik** [comment]
Yes

**Comment by oguzdelioglu** [comment]
> Yes

└─# ./brainflayer -v -b bloomlist.blf -i dictionary.txt
3e546d0acc0de5aa3d63a7a920900ecbc66c2031:u:sha256:password
3e546d0acc0de5aa3d63a7a920900ecbc66c2031:u:sha256:password
 rate:  90864.95 p/s found:     2/394748     elapsed:    4.344 s


scanning ends very quickly.
I wonder why bruteforce ends so fast?
I am using brainwallet dictionary

**Comment by Napulsnik** [comment]
How many lines in dictionary.txt?

**Comment by oguzdelioglu** [comment]
> How many lines in dictionary.txt?

https://github.com/dan-v/bruteforce-bitcoin-brainwallet/blob/master/dictionary.txt
394748

**Comment by Napulsnik** [comment]
Pay attention to the line:
`rate: 90864.95 p/s found: 2/394748 elapsed: 4.344 s`
This means that the program was running at speed 90864.95 passwords per second. Therefore your file with 394748 lines was processed in 4.344 seconds

**Comment by oguzdelioglu** [comment]
> Pay attention to the line:
> `rate: 90864.95 p/s found: 2/394748 elapsed: 4.344 s`
> This means that the program was running at speed 90864.95 passwords per second. Therefore your file with 394748 lines was processed in 4.344 seconds


Example Recovery
realize stare depth pour rape butterfly torture swim retreat space heartbeat garden



Doesn't the brainflayer try to generate 394,000 words by 12 randomly and match those in the bloom filter?
It doesn't make sense to query the word in each line alone.
Doesn't it make sense to convert 394 thousand words to 12 words random BIP39 and generate keys?

**Comment by Napulsnik** [comment]
The brainflayer simply processes the file with the dictionary line by line, or accepts lines through the pipe. The brainflayer does not generate dictionaries.

**Comment by oguzdelioglu** [comment]
> The brainflayer simply processes the file with the dictionary line by line, or accepts lines through the pipe. The brainflayer does not generate dictionaries.

3e546d0acc0de5aa3d63a7a920900ecbc66c2031:u:sha256:password


it gives a return in this way.

I wonder what does this sha256 mean?
Did he find a wallet?

**Comment by Napulsnik** [comment]
Yes. He found 1 wallet with the password "password". Brainwallet is a sha256 hash of a human-readable password.

brainwallet = password
sha256(password) = private key = 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
HASH160 for 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 = 3e546d0acc0de5aa3d66d7a920900ecbc66c2031

**Comment by oguzdelioglu** [comment]
> Yes. He found 1 wallet with the password "password". Brainwallet is a sha256 hash of a human-readable password.
> 
> brainwallet = password
> sha256(password) = private key = 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
> HASH160 for 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 = 3e546d0acc0de5aa3d66d7a920900ecbc66c2031
> address for 3e546d0acc0de5aa3d66d7a920900ecbc66c2031 = 16ga2uqnF1NqpAuQeeg7sTCAdtDUwDyJav

https://github.com/TheRealLordFractal/Bip39Helper
I found this project.
Its helping brute bip39 with dictionary for brainflayer.

the only thing I wonder is that someone can still find a wallet.

**Comment by oguzdelioglu** [comment]
> Yes. He found 1 wallet with the password "password". Brainwallet is a sha256 hash of a human-readable password.
> 
> brainwallet = password
> sha256(password) = private key = 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
> RIPEMD160 (Hash160) for 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8 = 3e546d0acc0de5aa3d66d7a920900ecbc66c2031
> Base58 address for 3e546d0acc0de5aa3d66d7a920900ecbc66c2031 = 16ga2uqnF1NqpAuQeeg7sTCAdtDUwDyJav

232 results found.
How will I check these results collectively?

620a1c4122342f22c3c61b4750d39e107be903f3:u:sha256: great n price human print 

For example I want to check results like this.

**Comment by Napulsnik** [comment]
What does "check" mean?

**Comment by oguzdelioglu** [comment]
> What does "check" mean?

How can I get the public addresses and private keys of those found collectively?
