### ISSUE TITLE
MultiChain support

### ISSUE THREAD

**Issue by andrewkrug** [ryancdotorg/brainflayer#15]
Hi there.  I'm just wondering if you could make this particular tool run against multichain instead of bitcoin and what file in particular I might need to edit to do that.  Thanks in advance.

**Comment by ryancdotorg** [comment]
Brainflayer works unmodified on most cryptocurrencies so long as they're using secp256k1 and the same pay-to-pubkey-hash algorithm as Bitcoin.

**Comment by ryancdotorg** [comment]
If you don't follow up with a further comment, I'm going to close this ticket tomorrow.

**Comment by andrewkrug** [comment]
Hey thanks.  You can go ahead and close the issue.  Much of what I want to do right now is theoretical in nature.  But thanks for the initial response.  :)

**Comment by ryancdotorg** [comment]
Cool. FWIW, I am planning on doing a bit of refactoring to allow other methods of computing the address from the public key (e.g. ethereum) to be added more easily in the future.
