### ISSUE TITLE
Won't compile on Arch Linux

### ISSUE THREAD

**Issue by InsideBall** [ryancdotorg/brainflayer#16]
$ make
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o warpwallet.o brainwalletio.o brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Makefile:59: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

$ pacman -Q openssl
openssl 1.0.2.f-1

$ pacman -Q gmp
gmp 6.1.0-3

**Comment by ryancdotorg** [comment]
Looks like the issue is that, by [by policy](https://lists.archlinux.org/pipermail/arch-dev-public/2013-October/025542.html) Arch does not include the .a versions of libraries for static linking. You'll have to modify the Makefile to use dynamic linking instead of static.
