### ISSUE TITLE
Replace bloom filter code

### ISSUE THREAD

**Issue by dasker** [ryancdotorg/brainflayer#160]
Hi, Ryan.

I want to increase the file size of the bloom filter.

Change #define BLOOM_SIZE variable to 1073741824
compiling and getting error while building
[!] Bloom filter file '/data/ad/hex8096.blf' is not the correct size (0! = 1073741824)
What else needs to be changed? Or is it a data type problem?
Thank you!

**Comment by ryancdotorg** [comment]
The bloom filter code currently in brainflayer can't trivially be modified to use a larger chunk of memory.

I have replacement in another repository that I intend to eventually integrate - https://rya.nc/gh/bloomslice - but I've got a number of other higher priority projects I'm currently working on.

**Comment by dasker** [comment]
Thanks for the quick response!
I admire your programming style!
