### ISSUE TITLE
-r or nonce search.

### ISSUE THREAD

**Issue by JamesC00** [ryancdotorg/brainflayer#172]
where can i find the version you made for the eleventh hope. i would love to play with the -r reuse but i lack the skills to mod BF myself. can i get a copy of it?

**Comment by ryancdotorg** [comment]
`-c x` is "most significant bits of x coordinate" which works with any supported private key method.

searching for nonce reuse is an entirely different problem and would require an entirely different program to implement

**Comment by JamesC00** [comment]
thank you for the feedback. is there a public program you used for nonce reuse or was that something you built for the talk? do you know of any? im sure i wont find anything at this point but i would love to do a audit of a few clone chains. anyway love your work. look foreword to your new stuff. the auto twitter blocking lists looks promising.

**Comment by ryancdotorg** [comment]
https://github.com/StealingBitcoinWithMath/StealingBitcoinWithMath

and

https://github.com/StealingBitcoinWithMath/ecdsapivot

It's been a long time, I tend to use ad-hoc shell one-lines _extensively_, and I wouldn't be surprised if that code no longer works, but... have fun.

**Comment by JamesC00** [comment]
ya i played with it a bit i hit the wall with the new bitcoinrpc changes in the last few years. the bitocin client changed and broke this, no prob. back to the drawing board. just means i need more coding. lol. i'll come back in a few months or so. thank you for the quick response.
