### ISSUE TITLE
How do I run it in Linux Mint

### ISSUE THREAD

**Issue by arko45bit** [ryancdotorg/brainflayer#173]
Im a noob a newcomer to the Linux ecosystem and for some time I was using Linux Mint got used to some basic terminal comands but now this is my first time seeing .c and .h files and I have no idea how to run this script I know its a noob question but it would really help if I can get an exp of running it

**Comment by ryancdotorg** [comment]
Unfortunately, I do not have time to hand-hold folks - and if you've never seen C files before it would take a lot of that.

Additionally, your other activity on GitHub implies your primary interest in Brainflayer is financial gain via theft, which is unethical, and I will not actively enable.

The reasons for the existence of this software:

1) To *prove* what an awful idea it is to generate keys from user provided seeds/passwords/passphrases. (accomplished, it caused brainwallet.org to shut down permanently)

2) To provide researchers a tool to analyze the scope of theft of cryptocurrency protected with such keys. (accomplished, it was used for multiple peer reviewed academic publications)

3) To demonstrate my programming skills. (accomplished, the right people were impressed)

Any private keys that could be found with this software, have been found. You won't find a key for a wallet with a balance. Unless *actual* research is your goal, using it will merely waste electricity.
