### ISSUE TITLE
Remove \r from string

### ISSUE THREAD

**Issue by XopMC** [ryancdotorg/brainflayer#174]
Salut!

Can you help me?
How can i remove "\r" character from string (ifile in brainflayer.c)

I need this to work successfully on Windows where line endings are CR+LR (\r\n )

**Comment by kenorb** [comment]
Try something like: https://github.com/kenorb-contrib/brainflayer/commit/58aa6da58c88a9585cfde099d9b897612a02daaa

**Comment by XopMC** [comment]
> Try something like: [kenorb-contrib@58aa6da](https://github.com/kenorb-contrib/brainflayer/commit/58aa6da58c88a9585cfde099d9b897612a02daaa)

I'll try it. Thank you!

**Comment by XopMC** [comment]
> Try something like: [kenorb-contrib@58aa6da](https://github.com/kenorb-contrib/brainflayer/commit/58aa6da58c88a9585cfde099d9b897612a02daaa)

Thank you so much!

Pipe on Windows works correctly 
![изображение](https://user-images.githubusercontent.com/89750173/173534243-8bdd6cf4-df36-46b5-bc58-0e97f1548f16.png)
