### ISSUE TITLE
How can I use Brainflater in Windows

### ISSUE THREAD

**Issue by chenzongshun** [ryancdotorg/brainflayer#176]
I have several idle Windows servers. I don't want to waste my computing power.
I tried to install Mingw on Windows, but always failed to make, so I can't run Brainflater.
Please help me.
![image](https://user-images.githubusercontent.com/40053656/190897478-690834f5-12e8-4656-9715-5d408be53c9e.png)

**Comment by ryancdotorg** [comment]
1. Computers use dramatically more electricity when the CPU is busy, so leaving them idle isn't a waste.
2. Unless you have specific partial knowledge of a key, you'll never crack anything that hasn't already been cracked.
3. Mingw is not a supported build target and never will be.
