### ISSUE TITLE
Detect CPU on Macbook Air M1 - Using Ubuntu on Docker

### ISSUE THREAD

**Issue by KyranMendoza1** [ryancdotorg/brainflayer#183]
Hi there,

I'm getting this error below when trying to run the make command.

Any advise on how to solve?

root@3432ce6c1b8b:/home/brainflayer# make
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainv2.o algo/brainwalletio.o algo/keccak.o algo/sha3.o algo/warpwallet.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -lpthread -o brainflayer
/usr/bin/ld: scrypt-jane/scrypt-jane.o: in function `scrypt_power_on_self_test':
scrypt-jane.c:(.text+0x1410): undefined reference to `detect_cpu'
/usr/bin/ld: scrypt-jane.c:(.text+0x1b1c): undefined reference to `detect_cpu'
/usr/bin/ld: scrypt-jane/scrypt-jane.o: in function `scrypt':
scrypt-jane.c:(.text+0x1f30): undefined reference to `detect_cpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1
root@3432ce6c1b8b:/home/brainflayer#

**Comment by ryancdotorg** [comment]
M1 is not a supported build architecture, only x86_64. The issue here is with [scrypt-jane](https://github.com/floodyberry/scrypt-jane/issues/12), which you *may* be able to resolve with that patch, but I can't help you otherwise.

If you'd like to send me an M1 Mac, I can see about making it work there. 🤷
