### ISSUE TITLE
gpu support

### ISSUE THREAD

**Issue by daedalus** [ryancdotorg/brainflayer#19]
is it possible through opencl?

**Comment by daedalus** [comment]
I don't feel up to the task but I think that the vanitygen opencl kernel will do the thing.

https://github.com/samr7/vanitygen/blob/master/calc_addrs.cl

I think it's just adding some glue.

**Comment by ryancdotorg** [comment]
The code from vanitygen is largely inapplicable -  it uses optimizations that allow it to search for arbitrary keypairs much faster than it could do a search for specific private keys.

As a result, it does not (as far as i can tell) contain a GPU accelerated function for computing a secp256k1 public key from a specific private key.

Also missing is an on-GPU bloom filter search.

Bandwidth to the GPU for transferring plaintext passwords and/or private keys is also a potential limiting factor.

There's no reason it shouldn't be possible to do the computations on a GPU, it's just that it mostly needs to be done from scratch.

**Comment by daedalus** [comment]
Thanks for the explanation
I'll try by my own to learn opencl and what I can come with.

**Comment by ryancdotorg** [comment]
If you get anywhere, please let me know. I've been thinking about doing it myself, but it's hard since I don't understand the math super well.

**Comment by mrsolgsm** [comment]
May be help this https://github.com/m1a1x1/Bloom_pattern_search ?
FPGA and OpenCL similar.

**Comment by Rsalazarm** [comment]
Hi guys! Just to know the status of this topic. Any news about brainflayer and GPU?

Regards!

**Comment by agoora** [comment]
Any news about brainflayer and implementation in OpenCL?
