### ISSUE TITLE
AutoConfigure

### ISSUE THREAD

**Issue by tukaanimhaka** [ryancdotorg/brainflayer#193]
Is there a way to store the last number in a file where the process can resume from in the cause of using the `-N` and `-I` options?

**Comment by ryancdotorg** [comment]
No. Write a wrapper script that tracks the values and runs brainflayer in batches - this is how it's designed to be used.

The data files used by brainflayer are memory mapped, so if you restart it again immediately with the same data files but different parameters it'll start back up near instantaneously.

**Comment by tukaanimhaka** [comment]
say i start with a number and give it a range to run until. `-N` how do I know where the process is in terms of how many numbers has it crunched so far?

**Comment by tukaanimhaka** [comment]
My intent is to start with a different value for `-I`. Not sure if that is possible currently?

**Comment by ryancdotorg** [comment]
There's a -v verbose flag that will put some status info on stderr.

Please note that if you're trying to make money by randomly hitting an address with a balance,

1. That's theft.

2. Your expected value would be much higher simply solo mining Bitcoin on CPU.

3. Incremental mode is slower than doubling mode, which is also less profitable than CPU mining.

4. There are significantly faster attacks for the puzzle transaction.

Unless you have partial knowledge of a specific private key, perhaps a damaged print out or something, there's no reason to use incremental mode.

**Comment by ryancdotorg** [comment]
Sure. You can do that with a simple shell script. But as I said in my other reply, there's no point unless you have a partial private key to start with.

You're more likely to hit three Powerball jackpots in a row than you are to find a collision with an address which has a balance running incremental mode for a year on a fast computer, and the electricity it'll cost you would buy a lot of lottery tickets.

**Comment by tukaanimhaka** [comment]
want to understand the process how this works. very interested in the blockchain space.

**Comment by battlenetcs** [comment]
> No. Write a wrapper script that tracks the values and runs brainflayer in batches - this is how it's designed to be used.
> 
> The data files used by brainflayer are memory mapped, so if you restart it again immediately with the same data files but different parameters it'll start back up near instantaneously.
> 
> On May 22, 2024 6:08:50 PM GMT+01:00, tukaanimhaka ***@***.***> wrote:
> >Is there a way to store the last number in a file where the process can resume from in the cause of using the `-N` and `-I` options? 
> >
> 

Truly angry reply🤣
