### ISSUE TITLE
"Does 130k guesses/second on my machine" ?

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [ryancdotorg/brainflayer#2]
Thanks for bringing attending to this and for sharing your research. I've played with libsecp256k1 using threads before and I was able to hit 75k/s on an i7 4970 using four threads. Looking at your code I find it difficult to understand how you're getting ~130k and how are you measuring it? 

uint64_t time_1, time_2;
int64_t time_delta;

Isn't used? Omitted code? Anyway you could share the metrics part? Thanks.

**Comment by ShaliDaliHaliDa** [comment]
int totalCounter = 0;
    time(&time_1);
    while (getline(&line, &line_sz, stdin) > 0) {
    ..
    .
         totalCounter++;
          time(&time_2);
          double elapsed = difftime(time_2,time_1);
          double speed = totalCounter/elapsed;
          if(totalCounter % 20000 == 0){
              printf("elapsed:%.f sec [speed:%.f/sec] total: %d\n", elapsed, speed, totalCounter);
          }
      }
      secp256k1_stop();

Results are 11K/s

    elapsed:76 sec [speed:11316/sec] total: 860000
    elapsed:78 sec [speed:11282/sec] total: 880000
    elapsed:80 sec [speed:11250/sec] total: 900000
    elapsed:82 sec [speed:11220/sec] total: 920000
    elapsed:83 sec [speed:11325/sec] total: 940000
    elapsed:85 sec [speed:11294/sec] total: 960000
    elapsed:87 sec [speed:11264/sec] total: 980000
    elapsed:89 sec [speed:11236/sec] total: 1000000
    elapsed:91 sec [speed:11209/sec] total: 1020000
    elapsed:92 sec [speed:11304/sec] total: 1040000
    elapsed:94 sec [speed:11277/sec] total: 1060000
    elapsed:96 sec [speed:11250/sec] total: 1080000
    elapsed:98 sec [speed:11224/sec] total: 1100000
    elapsed:99 sec [speed:11313/sec] total: 1120000
    elapsed:101 sec [speed:11287/sec] total: 1140000
    elapsed:103 sec [speed:11262/sec] total: 1160000
    elapsed:105 sec [speed:11238/sec] total: 1180000
    elapsed:107 sec [speed:11215/sec] total: 1200000
    elapsed:108 sec [speed:11296/sec] total: 1220000
    elapsed:110 sec [speed:11273/sec] total: 1240000
    elapsed:112 sec [speed:11250/sec] total: 1260000
    elapsed:114 sec [speed:11228/sec] total: 1280000

**Comment by ryancdotorg** [comment]
Will give more detail later, but my reference machine is an i7-2600. Eight processes, timing a word list of known size read from a ramdisk.

On August 9, 2015 8:27:55 PM PDT, ShaliDaliHaliDa <notifications@github.com> wrote:
>  int totalCounter = 0;
>    time(&time_1);
>    while (getline(&line, &line_sz, stdin) > 0) {
>    ..
>    .
>         totalCounter++;
>          time(&time_2);
>          double elapsed = difftime(time_2,time_1);
>          double speed = totalCounter/elapsed;
>          if(totalCounter % 20000 == 0){
>printf("elapsed:%.f sec [speed:%.f/sec] total: %d\n", elapsed, speed,
>totalCounter);
>          }
>      }
>      secp256k1_stop();
>
>Results are 11K/s
>
>    elapsed:76 sec [speed:11316/sec] total: 860000
>    elapsed:78 sec [speed:11282/sec] total: 880000
>    elapsed:80 sec [speed:11250/sec] total: 900000
>    elapsed:82 sec [speed:11220/sec] total: 920000
>    elapsed:83 sec [speed:11325/sec] total: 940000
>    elapsed:85 sec [speed:11294/sec] total: 960000
>    elapsed:87 sec [speed:11264/sec] total: 980000
>    elapsed:89 sec [speed:11236/sec] total: 1000000
>    elapsed:91 sec [speed:11209/sec] total: 1020000
>    elapsed:92 sec [speed:11304/sec] total: 1040000
>    elapsed:94 sec [speed:11277/sec] total: 1060000
>    elapsed:96 sec [speed:11250/sec] total: 1080000
>    elapsed:98 sec [speed:11224/sec] total: 1100000
>    elapsed:99 sec [speed:11313/sec] total: 1120000
>    elapsed:101 sec [speed:11287/sec] total: 1140000
>    elapsed:103 sec [speed:11262/sec] total: 1160000
>    elapsed:105 sec [speed:11238/sec] total: 1180000
>    elapsed:107 sec [speed:11215/sec] total: 1200000
>    elapsed:108 sec [speed:11296/sec] total: 1220000
>    elapsed:110 sec [speed:11273/sec] total: 1240000
>    elapsed:112 sec [speed:11250/sec] total: 1260000
>    elapsed:114 sec [speed:11228/sec] total: 1280000
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ryancdotorg/brainflayer/issues/2#issuecomment-129288288

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ShaliDaliHaliDa** [comment]
Thanks for responding. OK I have access to an 16-core with 100GB Memory, I can mount a temps / ramdisk too but I don't see how that would improve the performance. I am not trying to pick a fight, just trying to understand. Perhaps should post this on reddit to further investigate (some guys want to reserve github comments for bugs etc).

**Comment by ryancdotorg** [comment]
Close this, and file a feature request issue for a benchmark script. Remind me if I haven't responded in a week.

On August 9, 2015 8:50:57 PM PDT, ShaliDaliHaliDa <notifications@github.com> wrote:
>Thanks for responding. OK I have access to an 16-core with 100GB
>Memory, I can mount a temps / ramdisk too but I don't see how that
>would improve the performance. I am not trying to pick a fight, just
>trying to understand. Perhaps should post this on reddit to further
>investigate (some guys want to reserve github comments for bugs etc). 
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ryancdotorg/brainflayer/issues/2#issuecomment-129289842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ShaliDaliHaliDa** [comment]
Sounds good. Will do. Please don't leave us hanging ;-)

**Comment by ryancdotorg** [comment]
DEF CON just ended a few hours ago. I need to recover a bit. 

On August 9, 2015 8:58:20 PM PDT, ShaliDaliHaliDa <notifications@github.com> wrote:
>Sounds good. Will do. Please don't leave us hanging ;-)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ryancdotorg/brainflayer/issues/2#issuecomment-129291433

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ryancdotorg** [comment]
there's now a -v flag that'll show cracking speed
