### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by daedalus** [ryancdotorg/brainflayer#21]
Runing with a full bloomfilter up to block 430000 and the same hashes160.bin file I'm getting this strange "false positives?", I tought that with the binfile it would suppres them.

5dedfbf9ea599dd4e3ca6a80b333c472fd0b3f69:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
5dedfbf9ea599dd4e3ca6a80b333c472fd0b3f69:c:(hex)priv:303030303030303030303030303030303030303030303030303030303030303030
751e76e8199196d454941c45d1b3a323f1433bd6:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
751e76e8199196d454941c45d1b3a323f1433bd6:c:(hex)priv:303030303030303030303030303030303030303030303030303030303030303030
751e76e8199196d454941c45d1b3a323f1433bd6:c:(hex)priv/btc:3030303030303030303030303030303030303030303030303030303030303030
7a680f79f36210df493cee5f055c1af8a8348878:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
7a680f79f36210df493cee5f055c1af8a8348878:c:(hex)priv/btc:3030303030303030303030303030303030303030303030303030303030303030
7dd65592d0ab2fe0d0257d571abf032cd9db93dc:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
7dd65592d0ab2fe0d0257d571abf032cd9db93dc:c:(hex)priv/btc:3030303030303030303030303030303030303030303030303030303030303030
8f9dff39a81ee4abcbad2ad8bafff090415a2be8:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
8f9dff39a81ee4abcbad2ad8bafff090415a2be8:c:(hex)priv/btc:3030303030303030303030303030303030303030303030303030303030303030
c42e7ef92fdb603af844d064faad95db9bcdfd3d:c:(hex)priv:3030303030303030303030303030303030303030303030303030303030303030
fc7250a211deddc70ee5a2738de5f07817351cef:c:(hex)priv:3131313131313131313131313131313131313131313131313131313131313131
fc7250a211deddc70ee5a2738de5f07817351cef:c:(hex)priv/btc:3131313131313131313131313131313131313131313131313131313131313131

**Comment by ryancdotorg** [comment]
Did you sort the entries before making the hash160.bin, and make sure to do the hex to binary conversion? If you fail to do that, you'l get undefined behavior.

I'm working on rewriting the bloom filter code to have configurable parameters to avoid this.

**Comment by daedalus** [comment]
Yes, I made myself sure to have unique entries in the hash160.bin file.

**Comment by ryancdotorg** [comment]
Weird. I'm seeing this on one system but not another with the same static binary.

**Comment by daedalus** [comment]
I have re-sorted the hash160.bin file the problem is gone.
