### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by rg83rg** [ryancdotorg/brainflayer#22]
Hi,

Can you assist me with this error?

root@kali:~/Desktop/brainflayer-master# make all
git submodule init
fatal: Not a git repository (or any of the parent directories): .git
Makefile:17: recipe for target 'secp256k1/.libs/libsecp256k1.a' failed
make: *** [secp256k1/.libs/libsecp256k1.a] Error 128

**Comment by MarcoFalke** [comment]
@rg83rg Did you download the zip or did an actual clone `git clone https://github.com/ryancdotorg/brainflayer.git`?

**Comment by rg83rg** [comment]
I downloaded the zip file

**Comment by ryancdotorg** [comment]
Apparently the zip download doesn't work.
