### ISSUE TITLE
support multytreads

### ISSUE THREAD

**Issue by mrsolgsm** [ryancdotorg/brainflayer#23]
Does the modification program is planned to run in multiple threads? For example via the MPI. There is a fork here https://github.com/Jul1u5/brainflayer-parallelized but it uses the old code and crashes when large files or if in the password list is used in Chinese or Japanese characters.

**Comment by ryancdotorg** [comment]
No, I'm not going to add support for this. Please check the help, there are some options for dividing up a list so you can run multiple copies, and shared memory is used for the large data files.

**Comment by mrsolgsm** [comment]
If you use one computer, then you can split the file and launch processes separately. But when the network version of MPI. Here then we will have something of their own to develop. It's a pity. :(

**Comment by ryancdotorg** [comment]
I've run stuff with it as-is on dozens of computers at once. Don't need MPI.

**Comment by mrsolgsm** [comment]
If it is possible that more please.
