### ISSUE TITLE
make: *** [ec_pubkey_fast.o] Error 1

### ISSUE THREAD

**Issue by rg83rg** [ryancdotorg/brainflayer#27]
Hi,

I changed from Kali rolling to Ubuntu 14.04 as directed. i think I am close to getting Brainflayer up and running finally. Hopefully you can assist to get me past these errors and warning. Thanks in advance.

I have Bitcoin and secp256k1 installed and all dependencies as far as I tell. I am getting the attached warnings and error: https://paste.ubuntu.com/23660433

make: *** [ec_pubkey_fast.o] Error 1

**Comment by ryancdotorg** [comment]
I just tried on a fresh install of Ubuntu 14.04 64bit, and it worked fine. Are you trying to build on the 32 bit version? What does `uname -a` and `/cat /proc/cpuinfo` say?

**Comment by ryancdotorg** [comment]
The only other thing I can think of is that maybe you tried to use a more recent version of libsecp256k1 than is pinned, which won't work. You have to use the exact version referenced.

**Comment by ryancdotorg** [comment]
I'm going to close this tomorrow if you haven't responded.
