### ISSUE TITLE
Very slow!

### ISSUE THREAD

**Issue by lianagit** [ryancdotorg/brainflayer#3]
Even if you comment out the bloom-filter / matching code and just feed secp256k1 i.e.   secp256k1_ecdsa_pubkey_create(pub_chr, &pub_chr_sz, hash256, 0);  the same over and over again to eliminate bottlenecks.  secp256k1_ecdsa_pubkey_create() would not be able to generate 20k/s on an i7 yet alone over 100k as claimed by op. 

What am I missing here?

**Comment by VictorKTrujillo** [comment]
Wondering the exact same thing.

**Comment by ryancdotorg** [comment]
I answered this on other thread. The quoted speed is the combined speed of 8 instances on my i7-2600.

On August 10, 2015 10:17:44 AM PDT, VictorKTrujillo <notifications@github.com> wrote:
>Wondering the exact same thing. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ryancdotorg/brainflayer/issues/3#issuecomment-129531867

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Jul1u5** [comment]
I was able to parallelize the code with OpenMPI, but I only have a really old System x3950 (IBM) and on 14 old Cores I managed to pass about 50k lines/sec. Don't now exactly how many on one core but ill do some testing.

**Comment by ShaliDaliHaliDa** [comment]
Yes please that would be interesting. I think this code would work well with OpenMPI though not quite sure how to best tackle the inputs? Shared me?

**Comment by ryancdotorg** [comment]
An option has been added to process only every nth line as a slightly more convenient way to use multiple cores. Also note that brainflayer is now more than twice as fast.
