### ISSUE TITLE
Compilation issu on ubuntu 16.10

### ISSUE THREAD

**Issue by beuzathor** [ryancdotorg/brainflayer#31]
Hello,
I try to compile on ubuntu 16.10 but i have a problem for finalise this.
My error is that :  
`(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Makefile:43: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1
`
I reading other issues and i think apps are linked badly but i don't found how to replace them.
Do you have an idea for fix that ?

Thanks

**Comment by joegeto** [comment]
did you get to figure it out?

**Comment by ryancdotorg** [comment]
see #32
