### ISSUE TITLE
Getting undefined references

### ISSUE THREAD

**Issue by killyou007** [ryancdotorg/brainflayer#33]
hi @ryancdotorg 

when i am trying to compile i am getting this error

~/Downloads/blf$ gcc -o makefile brainflayer.c -w -v -static -I.Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/5/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
COLLECT_GCC_OPTIONS='-o' 'makefile' '-w' '-v' '-static' '-I' '.' '-mtune=generic' '-march=i686'
 /usr/lib/gcc/i686-linux-gnu/5/cc1 -quiet -v -I . -imultiarch i386-linux-gnu brainflayer.c -quiet -dumpbase brainflayer.c -mtune=generic -march=i686 -auxbase brainflayer -w -version -fstack-protector-strong -Wformat -Wformat-security -o /tmp/ccm1Qc42.s
GNU C11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (i686-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/usr/local/include/i386-linux-gnu"
ignoring nonexistent directory "/usr/lib/gcc/i686-linux-gnu/5/../../../../i686-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 .
 /usr/lib/gcc/i686-linux-gnu/5/include
 /usr/local/include
 /usr/lib/gcc/i686-linux-gnu/5/include-fixed
 /usr/include/i386-linux-gnu
 /usr/include
End of search list.
GNU C11 (Ubuntu 5.4.0-6ubuntu1~16.04.4) version 5.4.0 20160609 (i686-linux-gnu)
	compiled by GNU C version 5.4.0 20160609, GMP version 6.1.0, MPFR version 3.1.4, MPC version 1.0.3
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: a358ec1be7c7b648dc6b1dbf99809e3a
COLLECT_GCC_OPTIONS='-o' 'makefile' '-w' '-v' '-static' '-I' '.' '-mtune=generic' '-march=i686'
 as -v -W -I . --32 -o /tmp/ccV06gkS.o /tmp/ccm1Qc42.s
GNU assembler version 2.26.1 (i686-linux-gnu) using BFD version (GNU Binutils for Ubuntu) 2.26.1
COMPILER_PATH=/usr/lib/gcc/i686-linux-gnu/5/:/usr/lib/gcc/i686-linux-gnu/5/:/usr/lib/gcc/i686-linux-gnu/:/usr/lib/gcc/i686-linux-gnu/5/:/usr/lib/gcc/i686-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/i686-linux-gnu/5/:/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/:/usr/lib/gcc/i686-linux-gnu/5/../../../../lib/:/lib/i386-linux-gnu/:/lib/../lib/:/usr/lib/i386-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/i686-linux-gnu/5/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-o' 'makefile' '-w' '-v' '-static' '-I' '.' '-mtune=generic' '-march=i686'
 /usr/lib/gcc/i686-linux-gnu/5/collect2 -plugin /usr/lib/gcc/i686-linux-gnu/5/liblto_plugin.so -plugin-opt=/usr/lib/gcc/i686-linux-gnu/5/lto-wrapper -plugin-opt=-fresolution=/tmp/ccbCTXDH.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_eh -plugin-opt=-pass-through=-lc --sysroot=/ --build-id -m elf_i386 --hash-style=gnu --as-needed -static -z relro -o makefile /usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o /usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crti.o /usr/lib/gcc/i686-linux-gnu/5/crtbeginT.o -L/usr/lib/gcc/i686-linux-gnu/5 -L/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu -L/usr/lib/gcc/i686-linux-gnu/5/../../../../lib -L/lib/i386-linux-gnu -L/lib/../lib -L/usr/lib/i386-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/i686-linux-gnu/5/../../.. /tmp/ccV06gkS.o --start-group -lgcc -lgcc_eh -lc --end-group /usr/lib/gcc/i686-linux-gnu/5/crtend.o /usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crtn.o
/tmp/ccV06gkS.o: In function `uhash160':
brainflayer.c:(.text+0x235): undefined reference to `SHA256_Init'
brainflayer.c:(.text+0x24f): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x265): undefined reference to `SHA256_Final'
brainflayer.c:(.text+0x27b): undefined reference to `ripemd160_256'
/tmp/ccV06gkS.o: In function `chash160':
brainflayer.c:(.text+0x2fa): undefined reference to `SHA256_Init'
brainflayer.c:(.text+0x312): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x328): undefined reference to `SHA256_Final'
brainflayer.c:(.text+0x33e): undefined reference to `ripemd160_256'
/tmp/ccV06gkS.o: In function `ehash160':
brainflayer.c:(.text+0x38a): undefined reference to `SHA3_256_Init'
brainflayer.c:(.text+0x3a8): undefined reference to `SHA3_256_Update'
brainflayer.c:(.text+0x3be): undefined reference to `KECCAK_256_Final'
/tmp/ccV06gkS.o: In function `pass2priv':
brainflayer.c:(.text+0x443): undefined reference to `SHA256_Init'
brainflayer.c:(.text+0x45b): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x470): undefined reference to `SHA256_Final'
/tmp/ccV06gkS.o: In function `keccak2priv':
brainflayer.c:(.text+0x4c0): undefined reference to `SHA3_256_Init'
brainflayer.c:(.text+0x4db): undefined reference to `SHA3_256_Update'
brainflayer.c:(.text+0x4f3): undefined reference to `KECCAK_256_Final'
/tmp/ccV06gkS.o: In function `camp2priv':
brainflayer.c:(.text+0x543): undefined reference to `SHA3_256_Init'
brainflayer.c:(.text+0x55e): undefined reference to `SHA3_256_Update'
brainflayer.c:(.text+0x576): undefined reference to `KECCAK_256_Final'
brainflayer.c:(.text+0x594): undefined reference to `SHA3_256_Init'
brainflayer.c:(.text+0x5ae): undefined reference to `SHA3_256_Update'
brainflayer.c:(.text+0x5c6): undefined reference to `KECCAK_256_Final'
/tmp/ccV06gkS.o: In function `sha32priv':
brainflayer.c:(.text+0x629): undefined reference to `SHA3_256_Init'
brainflayer.c:(.text+0x644): undefined reference to `SHA3_256_Update'
brainflayer.c:(.text+0x65c): undefined reference to `SHA3_256_Final'
/tmp/ccV06gkS.o: In function `warppass2priv':
brainflayer.c:(.text+0x6bc): undefined reference to `warpwallet'
/tmp/ccV06gkS.o: In function `bwiopass2priv':
brainflayer.c:(.text+0x703): undefined reference to `brainwalletio'
/tmp/ccV06gkS.o: In function `brainv2pass2priv':
brainflayer.c:(.text+0x762): undefined reference to `brainv2'
/tmp/ccV06gkS.o: In function `warpsalt2priv':
brainflayer.c:(.text+0x7c9): undefined reference to `warpwallet'
/tmp/ccV06gkS.o: In function `bwiosalt2priv':
brainflayer.c:(.text+0x810): undefined reference to `brainwalletio'
/tmp/ccV06gkS.o: In function `brainv2salt2priv':
brainflayer.c:(.text+0x86f): undefined reference to `brainv2'
/tmp/ccV06gkS.o: In function `rush2priv':
brainflayer.c:(.text+0x8e7): undefined reference to `SHA256_Init'
brainflayer.c:(.text+0x902): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x918): undefined reference to `SHA256_Final'
brainflayer.c:(.text+0x92c): undefined reference to `hex'
brainflayer.c:(.text+0x93e): undefined reference to `SHA256_Init'
brainflayer.c:(.text+0x95d): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x975): undefined reference to `SHA256_Update'
brainflayer.c:(.text+0x98d): undefined reference to `SHA256_Final'
/tmp/ccV06gkS.o: In function `fprintresult':
brainflayer.c:(.text+0xa10): undefined reference to `hex'
/tmp/ccV06gkS.o: In function `main':

on Ubuntu
What would be the issue?

**Comment by ryancdotorg** [comment]
You appear to be invoking gcc directly to compile, rather than using the `make` command.
