### ISSUE TITLE
Problem with bloom filter (hex2blf)

### ISSUE THREAD

**Issue by Napulsnik** [ryancdotorg/brainflayer#37]
Hello. I have problem with bloom filter.

```
~/brainflayer# ./hex2blf addr.txt 123.blf
[*] Initializing bloom filter…
Killed
```

**Comment by ryancdotorg** [comment]
What are the specs of the system you're trying to run it on? That looks like the kernel killing the process because you don't have enough memory available. I suggest running on a system with at least 24GB of RAM for reasonable performance, though 8GB should be enough to run.

**Comment by Napulsnik** [comment]
Oh. I have only 256mb RAM on my server for 1$ )))

**Comment by ryancdotorg** [comment]
Not going to run on that.

**Comment by osman9815** [comment]
Hello
Please teach me how to make a bloom filter

**Comment by ryancdotorg** [comment]
Please don't post new questions to closed issues .
