### ISSUE TITLE
Ubuntu 14.04 compile fail

### ISSUE THREAD

**Issue by PowerPress** [ryancdotorg/brainflayer#4]
I keep getting the same error on compiling. What am I missing to test this. Thanks

choice@ubuntu:~/brainflayer$ make
git submodule init
git submodule update
cd secp256k1; make distclean || true
make[1]: Entering directory `/home/choice/brainflayer/secp256k1'
make[1]: *** No rule to make target `distclean'.  Stop.
make[1]: Leaving directory `/home/choice/brainflayer/secp256k1'
cd secp256k1; ./autogen.sh
./autogen.sh: 2: ./autogen.sh: autoreconf: not found
make: *** [secp256k1/.libs/libsecp256k1.a] Error 127
choice@ubuntu:~/brainflayer$

**Comment by llamasoft** [comment]
Install `autoreconf`.

https://askubuntu.com/questions/265471/autoreconf-not-found-error-during-making-qemu-1-4-0

**Comment by PowerPress** [comment]
Just installed but got hit with the following error:

choice@ubuntu:~/brainflayer$ make
git submodule init
git submodule update
cd secp256k1; make distclean || true
make[1]: Entering directory `/home/choice/brainflayer/secp256k1'
make[1]: *** No rule to make target `distclean'.  Stop.
make[1]: Leaving directory `/home/choice/brainflayer/secp256k1'
cd secp256k1; ./autogen.sh
configure.ac:12: installing 'src/build-aux/compile'
configure.ac:5: installing 'src/build-aux/config.guess'
configure.ac:5: installing 'src/build-aux/config.sub'
configure.ac:9: installing 'src/build-aux/install-sh'
configure.ac:9: installing 'src/build-aux/missing'
Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am:4: warning: source file 'src/secp256k1.c' is in a subdirectory,
Makefile.am:4: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:45: warning: source file 'src/bench.c' is in a subdirectory,
Makefile.am:45: but option 'subdir-objects' is disabled
Makefile.am:53: warning: source file 'src/tests.c' is in a subdirectory,
Makefile.am:53: but option 'subdir-objects' is disabled
Makefile.am: installing 'src/build-aux/depcomp'
parallel-tests: installing 'src/build-aux/test-driver'
autoreconf: automake failed with exit status: 1
make: *** [secp256k1/.libs/libsecp256k1.a] Error 1

**Comment by CrossingHeart66** [comment]
apt-get install libgmp-dev

**Comment by PowerPress** [comment]
Just did and get the following:

choice@ubuntu:~/brainflayer$ make
git submodule init
git submodule update
cd secp256k1; make distclean || true
make[1]: Entering directory `/home/choice/brainflayer/secp256k1'
make[1]: *** No rule to make target `distclean'.  Stop.
make[1]: Leaving directory `/home/choice/brainflayer/secp256k1'
cd secp256k1; ./autogen.sh
Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am:4: warning: source file 'src/secp256k1.c' is in a subdirectory,
Makefile.am:4: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
Makefile.am:45: warning: source file 'src/bench.c' is in a subdirectory,
Makefile.am:45: but option 'subdir-objects' is disabled
Makefile.am:53: warning: source file 'src/tests.c' is in a subdirectory,
Makefile.am:53: but option 'subdir-objects' is disabled
autoreconf: automake failed with exit status: 1
make: *** [secp256k1/.libs/libsecp256k1.a] Error 1

**Comment by ryancdotorg** [comment]
Works for me. This looks like a missing dependency for libsecp256k1, you'll have more luck asking in their github project.

**Comment by asam007** [comment]
I have a similar issue an all effort to get a fix has fail thus far, I use ubuntu 18.04 LTS

gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(b_addr.o): In function `BIO_lookup_ex':
(.text+0xcea): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
(.text+0x45): undefined reference to `pthread_rwlock_init'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
(.text+0x75): undefined reference to `pthread_rwlock_rdlock'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
(.text+0x95): undefined reference to `pthread_rwlock_wrlock'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_unlock':
(.text+0xb5): undefined reference to `pthread_rwlock_unlock'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
(.text+0xda): undefined reference to `pthread_rwlock_destroy'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_run_once':
(.text+0x105): undefined reference to `pthread_once'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_init_local':
(.text+0x125): undefined reference to `pthread_key_create'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_set_local':
(.text+0x157): undefined reference to `pthread_setspecific'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_cleanup_local':
(.text+0x177): undefined reference to `pthread_key_delete'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `openssl_init_fork_handlers':
(.text+0x1d3): undefined reference to `pthread_once'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_get_local':
(.text+0x143): undefined reference to `pthread_getspecific'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_eh.a(unwind-dw2.o): In function `uw_init_context_1':
(.text+0x1e91): undefined reference to `pthread_once'
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1
