### ISSUE TITLE
Where are matches stored?

### ISSUE THREAD

**Issue by SamLewis17** [ryancdotorg/brainflayer#42]
Ran through using $brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b sampleaccounts.blf
Got some matches. Is there anyway to pause/resume? or do I just close and re-open?

$brainflayer -b sampleaccounts.blf to check matches. nothing is returned. 

Thanks

**Comment by ryancdotorg** [comment]
As explained in the detailed usage info (displayed with `brainflayer -h`), the `-o` option will save matches to a file. You can pause brainflayer, like most programs on Linux, with `kill -STOP $pid` and resume with `kill -CONT $pid`.
