### ISSUE TITLE
how to use -k and -n ?

### ISSUE THREAD

**Issue by rawmaterials** [ryancdotorg/brainflayer#44]
[root@brainflayer]# ./brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b btcaddress.blf -f btcaddress.bin -k 5 -n 2

Invalid '-n' argument, remainder '2' must be <= modulus '0'

how can i use it ? what does this error mean ?

what is the flow ?

Thanks.

**Comment by ryancdotorg** [comment]
Please see the output of `brainflayer -h`, and read the source code if you still don't understand. Per the README, I don't provide usage support.
