### ISSUE TITLE
Problem bloom

### ISSUE THREAD

**Issue by gandiben** [ryancdotorg/brainflayer#52]
I'm asking for help
I use ubuntu 16.10. I have 8gb memory but I always get a bug for a bloom.
bit@bit:~/bit/brainflayer$ ./brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b example.blf
failed to open bloom filter 'example.blf': Incorrect file size
bit@bit:~/bit/brainflayer$ ./hex2blf bitc4.txt example.blf
[!] Bloom filter file 'example.blf' is not the correct size (0 != 536870912)
bit@bit:~/bit/brainflayer$

**Comment by ryancdotorg** [comment]
Your `example.blf` is an empty file, delete it.
