### ISSUE TITLE
Make Install Failing

### ISSUE THREAD

**Issue by lifelike99** [ryancdotorg/brainflayer#55]
After sucessfully running make,  I run make install and receive the error "No rule to make target 'install' stop". 

After if i try to run brainflayer i receive "no such command" 

Not sure what I've done wrong in the process?

**Comment by hevnsnt** [comment]
I do not believe there is an install target.  Your binary should be compiled in the existing directory.

**Comment by ryancdotorg** [comment]
No `install` target will be implemented.
