### ISSUE TITLE
Command line examples

### ISSUE THREAD

**Issue by duffusmucous** [ryancdotorg/brainflayer#58]
A complete command line call list,  with brief description,  would not hurt.  Most repositories have them.  I realize it may be a headache but it would really make testing this program more useful.  Also,  it would be helpful for developers who wish to contribute.

##############################################################################
1JryTePceSiWVpoNBU8SbwiT7J4ghzijzW
This message was signed
HEwctn6GVprhw1GUwg+1W3tJY28wu/uVC6TpD6VeFfW6BIVH0rApPCSIjzfga1Eq3iBFRJlXl43jtIgrMaCKKRE=
##############################################################################

**Comment by ryancdotorg** [comment]
The major command line options are described in the `README.md`, which also mentions that a more detailed list is available via `./brainflayer -h`.

-----BEGIN BITCOIN SIGNED MESSAGE-----
My signed message actually verifies.
-----BEGIN SIGNATURE-----
1JryTePceSiWVpoNBU8SbwiT7J4ghzijzW
G0onQXUwAS5lnWiWUhGgaRnvBWomxbgh5d+hlmtPrmvmuXxYfg0r4cm64wX0igg315n130Ah9XfnbyNthwuNIAQ=
-----END BITCOIN SIGNED MESSAGE-----
