### ISSUE TITLE
Incremental Method question

### ISSUE THREAD

**Issue by darito21** [ryancdotorg/brainflayer#64]
Hi
I was able to compile and use this tool. 
Im playing with the incremental hex method, but just curious, how can I add a list of address/hashes to check?
I mean, I have a list of 100 X address, then I run 
brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b example.blf
Is there any way to let the software know about the list that it must check? (my target address list).

Thank you

**Comment by komyak** [comment]
1)
hex2blf You100address_160.hex You100address.blf
2)brainflayer -v -I 0000000000000000000000000000000000000000000000000000000000000001 -b You100address.blf

**Comment by ryancdotorg** [comment]
This is explained in the readme - you need to get the addresses in hash160 format. There are tools for doing this, though I don't know any offhand.
