### ISSUE TITLE
0x prefix to eth address

### ISSUE THREAD

**Issue by Hanoosh** [ryancdotorg/brainflayer#66]
can you add the 0x prefix ?

`/* ethereum address */
static void ehash160(hash160_t *h, const unsigned char *upub) {
  SHA3_256_CTX ctx;
  unsigned char hash[SHA256_DIGEST_LENGTH];

  /* compute hash160 for uncompressed public key */
  /* keccak_256_last160(pub) */
  KECCAK_256_Init(&ctx);
  KECCAK_256_Update(&ctx, upub+1, 64);
  KECCAK_256_Final(hash, &ctx);
  **memcpy(h->uc, hash+12, 20)**;
}`

**Comment by ryancdotorg** [comment]
No.
