### ISSUE TITLE
make: *** [Makefile:68: brainflayer] Error 1

### ISSUE THREAD

**Issue by Grandspike** [ryancdotorg/brainflayer#68]
%^$#@!%*@kali:~/brainflayer# make

gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/bin/ld: /usr/lib/gcc/i686-linux-gnu/8/../../../i386-linux-gnu/libcrypto.a(b_addr.o): in function `BIO_lookup':
(.text+0xd68): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/i686-linux-gnu/8/../../../i386-linux-gnu/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
(.text+0x94): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
lto1: fatal error: bytecode stream in file ‘brainflayer.o’ generated with LTO version 6.0 instead of the expected 7.0
compilation terminated.
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [Makefile:68: brainflayer] Error 1
--------------------------------------------------------------
Kali Linux 2018.2-vm-i386
already installed autoconf, libtool, openssl, libssl-dev, glibc-source, libcrypto++-dev, libcrypto++-utils, libsecp256k1-0, libsecp256k1-dev, gcc, gcc-multilib-x86-64-linux-gnux32, gcc-7-multilib-x86-64-linux-gnux32, libsocket-getaddrinfo-perl. Updated & Upgraded, but I'm stuck. Please, help me.

**Comment by ryancdotorg** [comment]
Kali isn't a supported operating system
