### ISSUE TITLE
 if (argc == 2) {} else... in main()

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [ryancdotorg/brainflayer#7]
Wondering, what happens if we don't pass any arguments into brainflayer. What's the  if (argc == 2) {} else{ } part in main(), i.e. no arguments passed into brainflayer?

  fprintf(stdout, "%08x%08x%08x%08x%08x:u:%s\n",
                ntohl(hash160_uncmp.ul[0]),
                ntohl(hash160_uncmp.ul[1]),
                ntohl(hash160_uncmp.ul[2]),
                ntohl(hash160_uncmp.ul[3]),
                ntohl(hash160_uncmp.ul[4]),
                line);
        fprintf(stdout, "%08x%08x%08x%08x%08x:c:%s\n",
                ntohl(hash160_compr.ul[0]),
                ntohl(hash160_compr.ul[1]),
                ntohl(hash160_compr.ul[2]),
                ntohl(hash160_compr.ul[3]),
                ntohl(hash160_compr.ul[4]),
                line);

**Comment by llamasoft** [comment]
It prints the compressed and uncompressed public key hash (RIPEMD-160) of each input string without checking it against the bloom filter.
