### ISSUE TITLE
/usr/bin/x86_64-linux-gnu-ld: cannot find -lz /usr/bin/x86_64-linux-gnu-ld: cannot find -lgmp

### ISSUE THREAD

**Issue by aqui1991** [ryancdotorg/brainflayer#70]
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/bin/x86_64-linux-gnu-ld: cannot find -lz
/usr/bin/x86_64-linux-gnu-ld: cannot find -lgmp
//usr/local/lib/libcrypto.a(b_addr.o): In function `BIO_lookup_ex':
b_addr.c:(.text+0xcea): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

**Comment by ryancdotorg** [comment]
install libgmp-dev and zlib1g-dev or your distros equivalent

**Comment by aqui1991** [comment]
thanks @ryancdotorg  :)
