### ISSUE TITLE
//usr/local/lib/libcrypto.a(b_addr.o): In function `BIO_lookup_ex':    //usr/local/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':

### ISSUE THREAD

**Issue by aqui1991** [ryancdotorg/brainflayer#71]
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
//usr/local/lib/libcrypto.a(b_addr.o): In function `BIO_lookup_ex':
b_addr.c:(.text+0xcea): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libcrypto.a(b_sock.o): In function `BIO_gethostbyname':
b_sock.c:(.text+0x71): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_new':
threads_pthread.c:(.text+0x45): undefined reference to `pthread_rwlock_init'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_read_lock':
threads_pthread.c:(.text+0x75): undefined reference to `pthread_rwlock_rdlock'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_write_lock':
threads_pthread.c:(.text+0x95): undefined reference to `pthread_rwlock_wrlock'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_unlock':
threads_pthread.c:(.text+0xb5): undefined reference to `pthread_rwlock_unlock'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_lock_free':
threads_pthread.c:(.text+0xda): undefined reference to `pthread_rwlock_destroy'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_run_once':
threads_pthread.c:(.text+0x105): undefined reference to `pthread_once'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_init_local':
threads_pthread.c:(.text+0x125): undefined reference to `pthread_key_create'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_set_local':
threads_pthread.c:(.text+0x157): undefined reference to `pthread_setspecific'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_cleanup_local':
threads_pthread.c:(.text+0x177): undefined reference to `pthread_key_delete'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `openssl_init_fork_handlers':
threads_pthread.c:(.text+0x1f3): undefined reference to `pthread_once'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
//usr/local/lib/libcrypto.a(threads_pthread.o): In function `CRYPTO_THREAD_get_local':
threads_pthread.c:(.text+0x143): undefined reference to `pthread_getspecific'
/usr/lib/gcc/x86_64-linux-gnu/7/libgcc_eh.a(unwind-dw2.o): In function `uw_init_context_1':
(.text+0x1e91): undefined reference to `pthread_once'
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

**Comment by ryancdotorg** [comment]
Try using ubuntu 14.04 - builds are broken in many newer distros.
