### ISSUE TITLE
Performance plummeted

### ISSUE THREAD

**Issue by daedalus** [ryancdotorg/brainflayer#74]
After kernel upgrading to linux kernel 4.12+ on debian the performance of brainflayer seems to be impacted by the spectre/meltdown parches but switching back to linux kernel 4.9 doesnt seem to fix the issue.
 
This happens every time, it starts with a decent p/s rate and then plummets, cpu usage too.

I do not know where to look, I was suspecting of the microcode patches, is there any workarround?

 code/BTC/brainflayer/brainflayer -b $HOME/tmp/bloom.blf -m $HOME/tmp/tabfile.tab  -f $HOME/tmp/hash160.bin -v -a -o tmp/brains/I -I 000000000000000000000000000000000000000000000000000XXXXXXXXXXXXX
 rate: 261964.03 p/s found:     0/3145728    elapsed:   12.170 s
-> rate:   9904.55 p/s found:     0/4194304    elapsed:  118.066 s

**Comment by ryancdotorg** [comment]
I honestly have no idea how to even begin to troubleshoot that. As far as the microcode patches go, IIRC they are installed at boot time and don't otherwise survive a reboot. Try uninstalling the microcode update package?

**Comment by daedalus** [comment]
After executing it 30x times I got a decent p/s rate again, it's weird, I'm closing beacuse it's working now.
Thanks
