### ISSUE TITLE
new installed linux 9.5 make problem

### ISSUE THREAD

**Issue by hamnaz** [ryancdotorg/brainflayer#82]
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

any advice for this error

**Comment by hamnaz** [comment]
full
make
gcc -O3 -flto -funsigned-char -falign-functions=16 -falign-loops=16 -falign-jumps=16 -Wall -Wextra -Wno-pointer-sign -Wno-sign-compare -pedantic -std=gnu99 -static brainflayer.o hex.o bloom.o mmapf.o hsearchf.o ec_pubkey_fast.o ripemd160_256.o dldummy.o algo/brainwalletio.o algo/warpwallet.o algo/keccak.o algo/sha3.o algo/brainv2.o secp256k1/.libs/libsecp256k1.a scrypt-jane/scrypt-jane.o -lssl -lrt -lcrypto -lz -lgmp -o brainflayer
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
Makefile:68: recipe for target 'brainflayer' failed
make: *** [brainflayer] Error 1

**Comment by ryancdotorg** [comment]
There is no such thing as "Linux 9.5", did you perhaps mean Debain 9.5? Regardless, per the README only Ubuntu 14.04 and 16.04 are supported build targets.

You need the development libraries for OpenSSL, GMP, and Zlib to build. I can't help you install these.
