### ISSUE TITLE
fatal error: openssl/sha.h

### ISSUE THREAD

**Issue by hariharan2820** [ryancdotorg/brainflayer#91]
HI
I NEED HELP I AM USING WIN10 OS IN MY PC WHILE I TRY TO COMPILE IT IS NOT COMPILING AND GETTING THE FOLLOWING ERROR PLS HELP CONTACT ME AT VKAHARIHARAN@GMAIL.COM OR SKYPE LIVE:dreamtechsolution

RDX@BITCOIN ~/brain
$ gcc brainflayer.c
brainflayer.c:12:10: fatal error: openssl/sha.h: No such file or directory
#include <openssl/sha.h>
^~~~~~~~~~~~~~~
compilation terminated.
I AM USING CYGWIN64 AS TERMINAL

**Comment by ryancdotorg** [comment]
Cygwin will never be supported.
