### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by stereo4** [ryancdotorg/brainflayer#92]
Hi,
Is this still working?
I have download and extract brainflayer, when I type "hex2blf example.hex example.blf" as you mention, console respond "hex2blf not found". Same when type "brainflayer -h".
There are not many info about installation on "readme" file, can you help me please? I'm on Ubuntu 18.04.

Thanks in advance!

**Comment by komyaka** [comment]
Not download.
Need: git clone http...
make

**Comment by stereo4** [comment]
Also tried git clone...
make brainflayer?
Can you please tell me exactly?

Thanks a lot for your help!

**Comment by ryancdotorg** [comment]
It won't compile correctly on Ubuntu 18.04, use 14.04. I don't provide help compiling beyond that - please take the time to learn how to set up a build toolchain.
