### ISSUE TITLE
Sessions are saved?

### ISSUE THREAD

**Issue by stereonov** [ryancdotorg/brainflayer#94]
Hello, quick question please, when using bruteforse or dictionary and an operation is stopped (e.g. CTRL+C or restart system), when start again the session is saved and start to the point it has been stopped or it's start over from beginning?
Thanks

**Comment by ryancdotorg** [comment]
No, and this will not be implemented. It's fairly straightforward to write a wrapper script that runs brainflayer over batches of input.
