### ISSUE TITLE
My word generator + brainflayer?

### ISSUE THREAD

**Issue by pcmaster30** [ryancdotorg/brainflayer#95]
Hi, i'm just start using your program & saw this tutorial
`your_generator | brainflayer -v -b example.blf
`
Does this mean we can use a word generator next to your program? How do we do it?

**Comment by ryancdotorg** [comment]
Sorry, I don't have time to provide help with usage.

**Comment by pcmaster30** [comment]
Would you at least suggest example about word generator? Thank You
