### ISSUE TITLE
Check trillions of passphase

### ISSUE THREAD

**Issue by ttran242** [ryancdotorg/brainflayer#96]
I read a few post that brainflayer checked trillions of passphases in less than a day using AWS. May i ask what the trick behind this? As far as i know, list of billlons of passphases already take up to GBs of hard drive let alone trillions. 
1/Did brainflayer really performs thsi fast on CPU?
2/Do you use wordlist to run this or generate passphase & compare it at the same time?

**Comment by ryancdotorg** [comment]
I have increased limited on my AWS account that allow me to run dozens of spot instances at once. This was combined with a job queuing system that I will not be releasing (don't ask). Some passphrases made by taking a large list and altering them in various ways based on rules, others were generated algorithmically.
