### ISSUE TITLE
Problem with pipe generator vs list

### ISSUE THREAD

**Issue by ttran242** [ryancdotorg/brainflayer#98]
So i combine my word generator with brainflayer like you said & notice this:

> 96f474e167ce5ac5f909e2a73f1694fe2134892d:u:sha256:036
> 8796d1a6f8bb36e2d54b3c6f4322921389a18a63:u:sha256:134
> 75e0a465ba918a5e062f95d5ccd5f3a5da3f7710:u:sha256:207
> ddfa7602f3447cb6b502ed60434526169e97d560:u:sha256:985

`vanmin |  ./brainflayer -v -b vidu.blf`
It generate orderly from 0 to 1000 & found the upper result in a heartbeat, same result when i try with maskprocessor
`mp64 ?d?d?d?d  |  ./brainflayer -v -b vidu.blf`

But when i test with the passphase list, none of them was found, even same passphase was put on txt file
` ./brainflayer -v  -b vidu.blf -i testpassword.txt`
At first i thought i accidently put few space in them but i checked it again & all the passphase was correct. Is there something wrong with brainflayer when check passphase list?

**Comment by komyaka** [comment]
brainflayer пропускает очень много паролей.
Как ты и сказал, разные генераторы выдают разные результаты.


brainflayer skips a lot of passwords.
Like you said, different generators produce different results.

**Comment by ttran242** [comment]
> brainflayer пропускает очень много паролей.
> Как ты и сказал, разные генераторы выдают разные результаты.
> 
> brainflayer skips a lot of passwords.
> Like you said, different generators produce different results.

I even try one passphase, just ONE & it wasn't found either

**Comment by B10wfish** [comment]
you can remove false positives with` -f example.bin`

**Comment by ttran242** [comment]
> you can remove false positives with` -f example.bin`

I just tried this, none was found either, somehting must be wrong with load passphase list function

**Comment by komyaka** [comment]
-f example.bin не правильно работает, с этим параметром пропускаются очень много паролей.

 -f example.bin не правильно работает, с этим параметром пропускаются очень много паролей.

- f example.bin does not work correctly, a lot of passwords are skipped with this parameter.

**Comment by komyaka** [comment]
ttran242 , you use 
my generator | maskprocessor | brainflayer
?

**Comment by ttran242** [comment]
No,i just run it as instructed 
‘maskprocessor | brainflayer’ 
first case was my own generator, second was maskprocessor. they all return results, unlike passphase list

**Comment by komyaka** [comment]
Не только это. Такое чувство, что brainflayer со списком stdin  работает не корректно.
Я работаю hashcat | brainflayer и при нахождении пароля начинает повторяться...

brainflayer, в том варианте это мамонт, который себя изжил. Не пользуюсь им 2 месяца, после того как написали новую программу gpu.
В brainflayer плюсы, что он будет работать на любом компе, даже с маленькими характеристиками.

Not just that. The feeling that brainflayer list stdin does not work properly.
I am running hashcat / brainflayer and when finding the password starts to repeat...
brainflayer such option is the mammoth, which have outlived their usefulness. I do not use it for 2 months after I wrote a new gpu program.
In brainflayer pros that it will work on any computer, even with small characteristics.

**Comment by B10wfish** [comment]
> I do not use it for 2 months after I wrote a new gpu program.

What is this program?

**Comment by komyaka** [comment]
Приватная программа, работает в риге 8 amd. 
На assume md работает очень медленно, максимум 3000000-6000000 h/s, на nvidia, должно быстрее.
Проблемы есть: нужно оперативки не менее 8 гб и файл с ethereum MAX 100 mb.
У меня 8 rigs, так что компенсирую количеством.
писали мне на заказ. Brainwallet btc, eth


Private program, works in Riga 8 amd. 
Assume for the md runs very slow, high 5000000-6000000 h/s on amd, nvidia must faster x2-3.
There are problems: you need at least 8 GB of RAM and a file with ethereum MAX 100 mb.
I have 8 rigs, so that compensate for number of.
write me to request. Brainwallet btc, eth

**Comment by ryancdotorg** [comment]
If you generate the text input file as `mp64 ?d?d?d?d > testpassword.txt` does it work? The same input reading code is used both for files and stdin, so I don't know why there would be any trouble so long as the data is the same.

If you don't sort the hash160 hash values before making the bin file, it won't work correctly, and no attempt is made to detect this condition.

**Comment by komyaka** [comment]
If you don't sort the hash160 hash values before making the bin file, it won't work correctly, and no attempt is made to detect this condition.

???
sort -u  or?

**Comment by ttran242** [comment]
the problem isn’t sorting, i did sort the hash list when load from passphase & it still didn’t work. i tried case when i put one single hash & one single passphase of it, it did load the file but didn’t calculate the passphase into the hash

**Comment by Napulsnik** [comment]
> Приватная программа, работает в риге 8 amd.
> На assume md работает очень медленно, максимум 3000000-6000000 h/s, на nvidia, должно быстрее.
> Проблемы есть: нужно оперативки не менее 8 гб и файл с ethereum MAX 100 mb.
> У меня 8 rigs, так что компенсирую количеством.
> писали мне на заказ. Brainwallet btc, eth
> 
> Private program, works in Riga 8 amd.
> Assume for the md runs very slow, high 5000000-6000000 h/s on amd, nvidia must faster x2-3.
> There are problems: you need at least 8 GB of RAM and a file with ethereum MAX 100 mb.
> I have 8 rigs, so that compensate for number of.
> write me to request. Brainwallet btc, eth
Привет. Во сколько обошлась разработка аналога brainflayer для GPU?

**Comment by ryancdotorg** [comment]
Please do not advertise here.

**Comment by ryancdotorg** [comment]
Only think I can think of going wrong here is issues with buffering, but brainflayer uses the exact same code to process via a pipe or a file once input is open.

For `-f`, you need to do `sort -u hash160.hex | xxd -r -p > hash160.bin`.

**Comment by BarrowHill** [comment]
ryancdotorg, please tell me, 
1)we need to sort only if we use -f option?
2)Any opinion for sorting base58.txt addresses list befor making hex file from it?
3)Any opinion for sorting btcaddress.hex before making bloom filter from it?
4)Why blf file is about 530Mb is my file contains only 82 lines? And why it is again about 500Mb when list contains 20-30 million rows?

**Comment by ryancdotorg** [comment]
> we need to sort only if we use -f option?

You should not use brainflayer without the `-f` option.

> Any reason for sorting base58.txt addresses list befor making hex file from it?

That would be a waste of time, they won't be sorted after converting to hex because of how base85 works.

> Any reason for sorting btcaddress.hex before making bloom filter from it?

You need to sort for the `-f` option, which you should not use brainflayer without.

> Why blf file is about 530Mb if my file contains only 82 lines? And why it is again about 500Mb when list contains 20-30 million rows?

Bloom filter parameters are fixed for performance reasons. I did some work on allowing different sizes, but have not finished.
