### ISSUE TITLE
What does the c in 'hash:c:sha256:password' mean?

### ISSUE THREAD

**Issue by brizzbane** [ryancdotorg/brainflayer#99]
**I'm "guessing", that 'u' means unencrypted (or uncompressed?), and 'c' means encrypted (or compressed?).**  But I am just guessing, and _if that is the case_, **how is the encryption (or compression) generated to test the password with the hash?**

I looked through the issues, and found issues for ':u:sha256', but not for ':c:sha256'.  I also Googled "brainflayer" ":c:sha256:", and there were no results.  I know you are busy, but I'm hoping you can provide me some direction...

My Testing:

Using this tool online, I generate a brain wallet to test:

> http://gobittest.appspot.com/Brainwallet

I input 'test' as the BrainWallet password, and get the address:
> btc address: 1HKqKTMpBTZZ8H5zcqYEWYBaaWELrDEXeE

I understand this:
```
address_to_hash160('1HKqKTMpBTZZ8H5zcqYEWYBaaWELrDEXeE')
hash160: b311d5766f9623408747554bcdec1d8dc05eeaf0 
```

Run Brainflayer:

> ./brainflayer/brainflayer -b btcaddress.blf -i passwords.txt -v
> b311d5766f9623408747554bcdec1d8dc05eeaf0:u:sha256:test
>  rate:      7.42 p/s found:     1/1          elapsed:    0.135 s
> 

Then take that hash and convert it back to an address:

```
hash160_to_address('b311d5766f9623408747554bcdec1d8dc05eeaf0')
btc address: 1HKqKTMpBTZZ8H5zcqYEWYBaaWELrDEXeE
```

However, when running Brainflayer, and getting an output like this:

> ./brainflayer/brainflayer -b btcaddress.blf -i passwords2.txt -v
> b311d5766f9623408747554bcdec1d8dc05eeaf0:u:sha256:test
> 3462e57e39772cc2a57a79a855bd1ae624d658c1:c:sha256:323232
>  rate:     20.83 p/s found:     2/2          elapsed:    0.096 s

When using:

> http://gobittest.appspot.com/Brainwallet

with the password '323232', I get:

```
btc address: 1Gdw9D5zkm9eqtTtNkBaziQ3LZqvHaSary
hash160: ab860e7373af5d67c6841787c31590083e9bccd5
```
which doesn't match the hash that Brainflayer found above:

`b311d5766f9623408747554bcdec1d8dc05eeaf0`

**So my conclusion is that the ":c:" must mean that Brainflayer is doing something with the password..** but searching here and Google, I haven't figured out what. Can provide me with any insight or direction?

Thank you so much.

**Comment by AllViewX** [comment]
c:sha256:password = commpresed
privkey Uncompressed : 5KTQfktMC6tF9TKfLqdXYGGn7zUbwKx8ScgEMLhDE6PVa7y1xpP
privkey Compressed  : L4TZU4he7zyBSKBNEZeDnzQe9rgqCneKr4U9vmvUxnnH6uS7CE6b
privkey Hex: D7FC9114DE64DCBFB105BF445C20967D1CBAEF8696EB596A1D936EFA915E5AE7
Uncompressed : 1LYYLk1UxrMSxPp3KGF8FnGbUppTymokbs
Compressed :     1CmxWVaAfFWetCSwkYMDj2YAJKjZj3s9eS

**Comment by ryancdotorg** [comment]
Please check out my slides from DEF CON - they walk through how passwords are processed starting on slide 8.

https://rya.nc/cracking_cryptocurrency_brainwallets.pdf
